%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'SW_Estimation_REE_expData_forMCMC';
M_.dynare_version = '4.6.1';
oo_.dynare_version = '4.6.1';
options_.dynare_version = '4.6.1';
%
% Some global variables initialization
%
global_initialization;
diary off;
options_.nograph = true;
options_.nointeractive = true;
M_.exo_names = cell(8,1);
M_.exo_names_tex = cell(8,1);
M_.exo_names_long = cell(8,1);
M_.exo_names(1) = {'eta_a'};
M_.exo_names_tex(1) = {'eta\_a'};
M_.exo_names_long(1) = {'eta_a'};
M_.exo_names(2) = {'eta_b'};
M_.exo_names_tex(2) = {'eta\_b'};
M_.exo_names_long(2) = {'eta_b'};
M_.exo_names(3) = {'eta_g'};
M_.exo_names_tex(3) = {'eta\_g'};
M_.exo_names_long(3) = {'eta_g'};
M_.exo_names(4) = {'eta_i'};
M_.exo_names_tex(4) = {'eta\_i'};
M_.exo_names_long(4) = {'eta_i'};
M_.exo_names(5) = {'eta_r'};
M_.exo_names_tex(5) = {'eta\_r'};
M_.exo_names_long(5) = {'eta_r'};
M_.exo_names(6) = {'eta_p'};
M_.exo_names_tex(6) = {'eta\_p'};
M_.exo_names_long(6) = {'eta_p'};
M_.exo_names(7) = {'eta_w'};
M_.exo_names_tex(7) = {'eta\_w'};
M_.exo_names_long(7) = {'eta_w'};
M_.exo_names(8) = {'eta_pi_exp'};
M_.exo_names_tex(8) = {'eta\_pi\_exp'};
M_.exo_names_long(8) = {'eta_pi_exp'};
M_.endo_names = cell(34,1);
M_.endo_names_tex = cell(34,1);
M_.endo_names_long = cell(34,1);
M_.endo_names(1) = {'mc'};
M_.endo_names_tex(1) = {'mc'};
M_.endo_names_long(1) = {'mc'};
M_.endo_names(2) = {'zcap'};
M_.endo_names_tex(2) = {'zcap'};
M_.endo_names_long(2) = {'zcap'};
M_.endo_names(3) = {'rk'};
M_.endo_names_tex(3) = {'rk'};
M_.endo_names_long(3) = {'rk'};
M_.endo_names(4) = {'k'};
M_.endo_names_tex(4) = {'k'};
M_.endo_names_long(4) = {'k'};
M_.endo_names(5) = {'q'};
M_.endo_names_tex(5) = {'q'};
M_.endo_names_long(5) = {'q'};
M_.endo_names(6) = {'c'};
M_.endo_names_tex(6) = {'c'};
M_.endo_names_long(6) = {'c'};
M_.endo_names(7) = {'inve'};
M_.endo_names_tex(7) = {'inve'};
M_.endo_names_long(7) = {'inve'};
M_.endo_names(8) = {'y'};
M_.endo_names_tex(8) = {'y'};
M_.endo_names_long(8) = {'y'};
M_.endo_names(9) = {'lab'};
M_.endo_names_tex(9) = {'lab'};
M_.endo_names_long(9) = {'lab'};
M_.endo_names(10) = {'pinf'};
M_.endo_names_tex(10) = {'pinf'};
M_.endo_names_long(10) = {'pinf'};
M_.endo_names(11) = {'w'};
M_.endo_names_tex(11) = {'w'};
M_.endo_names_long(11) = {'w'};
M_.endo_names(12) = {'r'};
M_.endo_names_tex(12) = {'r'};
M_.endo_names_long(12) = {'r'};
M_.endo_names(13) = {'kp'};
M_.endo_names_tex(13) = {'kp'};
M_.endo_names_long(13) = {'kp'};
M_.endo_names(14) = {'eps_a'};
M_.endo_names_tex(14) = {'eps\_a'};
M_.endo_names_long(14) = {'eps_a'};
M_.endo_names(15) = {'eps_b'};
M_.endo_names_tex(15) = {'eps\_b'};
M_.endo_names_long(15) = {'eps_b'};
M_.endo_names(16) = {'eps_g'};
M_.endo_names_tex(16) = {'eps\_g'};
M_.endo_names_long(16) = {'eps_g'};
M_.endo_names(17) = {'eps_i'};
M_.endo_names_tex(17) = {'eps\_i'};
M_.endo_names_long(17) = {'eps_i'};
M_.endo_names(18) = {'eps_r'};
M_.endo_names_tex(18) = {'eps\_r'};
M_.endo_names_long(18) = {'eps_r'};
M_.endo_names(19) = {'eps_p'};
M_.endo_names_tex(19) = {'eps\_p'};
M_.endo_names_long(19) = {'eps_p'};
M_.endo_names(20) = {'eps_w'};
M_.endo_names_tex(20) = {'eps\_w'};
M_.endo_names_long(20) = {'eps_w'};
M_.endo_names(21) = {'pinf_exp'};
M_.endo_names_tex(21) = {'pinf\_exp'};
M_.endo_names_long(21) = {'pinf_exp'};
M_.endo_names(22) = {'labobs'};
M_.endo_names_tex(22) = {'labobs'};
M_.endo_names_long(22) = {'labobs'};
M_.endo_names(23) = {'robs'};
M_.endo_names_tex(23) = {'robs'};
M_.endo_names_long(23) = {'robs'};
M_.endo_names(24) = {'cpi_quarterly'};
M_.endo_names_tex(24) = {'cpi\_quarterly'};
M_.endo_names_long(24) = {'cpi_quarterly'};
M_.endo_names(25) = {'dy'};
M_.endo_names_tex(25) = {'dy'};
M_.endo_names_long(25) = {'dy'};
M_.endo_names(26) = {'dc'};
M_.endo_names_tex(26) = {'dc'};
M_.endo_names_long(26) = {'dc'};
M_.endo_names(27) = {'dinve'};
M_.endo_names_tex(27) = {'dinve'};
M_.endo_names_long(27) = {'dinve'};
M_.endo_names(28) = {'dw'};
M_.endo_names_tex(28) = {'dw'};
M_.endo_names_long(28) = {'dw'};
M_.endo_names(29) = {'inf_fore_1_4'};
M_.endo_names_tex(29) = {'inf\_fore\_1\_4'};
M_.endo_names_long(29) = {'inf_fore_1_4'};
M_.endo_names(30) = {'pinf_exp_noshock'};
M_.endo_names_tex(30) = {'pinf\_exp\_noshock'};
M_.endo_names_long(30) = {'pinf_exp_noshock'};
M_.endo_names(31) = {'pinf_exp_tt1'};
M_.endo_names_tex(31) = {'pinf\_exp\_tt1'};
M_.endo_names_long(31) = {'pinf_exp_tt1'};
M_.endo_names(32) = {'AUX_ENDO_LEAD_366'};
M_.endo_names_tex(32) = {'AUX\_ENDO\_LEAD\_366'};
M_.endo_names_long(32) = {'AUX_ENDO_LEAD_366'};
M_.endo_names(33) = {'AUX_ENDO_LEAD_370'};
M_.endo_names_tex(33) = {'AUX\_ENDO\_LEAD\_370'};
M_.endo_names_long(33) = {'AUX_ENDO_LEAD_370'};
M_.endo_names(34) = {'AUX_ENDO_LEAD_326'};
M_.endo_names_tex(34) = {'AUX\_ENDO\_LEAD\_326'};
M_.endo_names_long(34) = {'AUX_ENDO_LEAD_326'};
M_.endo_partitions = struct();
M_.param_names = cell(34,1);
M_.param_names_tex = cell(34,1);
M_.param_names_long = cell(34,1);
M_.param_names(1) = {'curvw'};
M_.param_names_tex(1) = {'curvw'};
M_.param_names_long(1) = {'curvw'};
M_.param_names(2) = {'curvp'};
M_.param_names_tex(2) = {'curvp'};
M_.param_names_long(2) = {'curvp'};
M_.param_names(3) = {'rho_ga'};
M_.param_names_tex(3) = {'rho\_ga'};
M_.param_names_long(3) = {'rho_ga'};
M_.param_names(4) = {'delta'};
M_.param_names_tex(4) = {'delta'};
M_.param_names_long(4) = {'delta'};
M_.param_names(5) = {'phi_w'};
M_.param_names_tex(5) = {'phi\_w'};
M_.param_names_long(5) = {'phi_w'};
M_.param_names(6) = {'l_bar'};
M_.param_names_tex(6) = {'l\_bar'};
M_.param_names_long(6) = {'l_bar'};
M_.param_names(7) = {'pi_bar'};
M_.param_names_tex(7) = {'pi\_bar'};
M_.param_names_long(7) = {'pi_bar'};
M_.param_names(8) = {'beta_const'};
M_.param_names_tex(8) = {'beta\_const'};
M_.param_names_long(8) = {'beta_const'};
M_.param_names(9) = {'alpha'};
M_.param_names_tex(9) = {'alpha'};
M_.param_names_long(9) = {'alpha'};
M_.param_names(10) = {'gamma_bar'};
M_.param_names_tex(10) = {'gamma\_bar'};
M_.param_names_long(10) = {'gamma_bar'};
M_.param_names(11) = {'mu_w'};
M_.param_names_tex(11) = {'mu\_w'};
M_.param_names_long(11) = {'mu_w'};
M_.param_names(12) = {'mu_p'};
M_.param_names_tex(12) = {'mu\_p'};
M_.param_names_long(12) = {'mu_p'};
M_.param_names(13) = {'psi'};
M_.param_names_tex(13) = {'psi'};
M_.param_names_long(13) = {'psi'};
M_.param_names(14) = {'phi'};
M_.param_names_tex(14) = {'phi'};
M_.param_names_long(14) = {'phi'};
M_.param_names(15) = {'lambda'};
M_.param_names_tex(15) = {'lambda'};
M_.param_names_long(15) = {'lambda'};
M_.param_names(16) = {'phi_p'};
M_.param_names_tex(16) = {'phi\_p'};
M_.param_names_long(16) = {'phi_p'};
M_.param_names(17) = {'iota_w'};
M_.param_names_tex(17) = {'iota\_w'};
M_.param_names_long(17) = {'iota_w'};
M_.param_names(18) = {'xi_w'};
M_.param_names_tex(18) = {'xi\_w'};
M_.param_names_long(18) = {'xi_w'};
M_.param_names(19) = {'iota_p'};
M_.param_names_tex(19) = {'iota\_p'};
M_.param_names_long(19) = {'iota_p'};
M_.param_names(20) = {'xi_p'};
M_.param_names_tex(20) = {'xi\_p'};
M_.param_names_long(20) = {'xi_p'};
M_.param_names(21) = {'sigma_c'};
M_.param_names_tex(21) = {'sigma\_c'};
M_.param_names_long(21) = {'sigma_c'};
M_.param_names(22) = {'sigma_l'};
M_.param_names_tex(22) = {'sigma\_l'};
M_.param_names_long(22) = {'sigma_l'};
M_.param_names(23) = {'r_pi'};
M_.param_names_tex(23) = {'r\_pi'};
M_.param_names_long(23) = {'r_pi'};
M_.param_names(24) = {'r_dy'};
M_.param_names_tex(24) = {'r\_dy'};
M_.param_names_long(24) = {'r_dy'};
M_.param_names(25) = {'r_y'};
M_.param_names_tex(25) = {'r\_y'};
M_.param_names_long(25) = {'r_y'};
M_.param_names(26) = {'rho'};
M_.param_names_tex(26) = {'rho'};
M_.param_names_long(26) = {'rho'};
M_.param_names(27) = {'G'};
M_.param_names_tex(27) = {'G'};
M_.param_names_long(27) = {'G'};
M_.param_names(28) = {'rho_a'};
M_.param_names_tex(28) = {'rho\_a'};
M_.param_names_long(28) = {'rho_a'};
M_.param_names(29) = {'rho_b'};
M_.param_names_tex(29) = {'rho\_b'};
M_.param_names_long(29) = {'rho_b'};
M_.param_names(30) = {'rho_p'};
M_.param_names_tex(30) = {'rho\_p'};
M_.param_names_long(30) = {'rho_p'};
M_.param_names(31) = {'rho_w'};
M_.param_names_tex(31) = {'rho\_w'};
M_.param_names_long(31) = {'rho_w'};
M_.param_names(32) = {'rho_i'};
M_.param_names_tex(32) = {'rho\_i'};
M_.param_names_long(32) = {'rho_i'};
M_.param_names(33) = {'rho_r'};
M_.param_names_tex(33) = {'rho\_r'};
M_.param_names_long(33) = {'rho_r'};
M_.param_names(34) = {'rho_g'};
M_.param_names_tex(34) = {'rho\_g'};
M_.param_names_long(34) = {'rho_g'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 8;
M_.endo_nbr = 34;
M_.param_nbr = 34;
M_.orig_endo_nbr = 31;
M_.aux_vars(1).endo_index = 32;
M_.aux_vars(1).type = 0;
M_.aux_vars(1).orig_expr = 'pinf(1)';
M_.aux_vars(2).endo_index = 33;
M_.aux_vars(2).type = 0;
M_.aux_vars(2).orig_expr = 'AUX_ENDO_LEAD_366(1)';
M_.aux_vars(3).endo_index = 34;
M_.aux_vars(3).type = 0;
M_.aux_vars(3).orig_expr = 'AUX_ENDO_LEAD_370(1)';
options_.varobs = cell(8, 1);
options_.varobs(1)  = {'dy'};
options_.varobs(2)  = {'dc'};
options_.varobs(3)  = {'dinve'};
options_.varobs(4)  = {'labobs'};
options_.varobs(5)  = {'cpi_quarterly'};
options_.varobs(6)  = {'dw'};
options_.varobs(7)  = {'robs'};
options_.varobs(8)  = {'inf_fore_1_4'};
options_.varobs_id = [ 25 26 27 22 24 28 23 29  ];
M_.Sigma_e = zeros(8, 8);
M_.Correlation_matrix = eye(8, 8);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.linear_decomposition = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 31;
M_.eq_nbr = 34;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 4;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 4;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 16 0;
 0 17 0;
 0 18 50;
 0 19 0;
 0 20 51;
 1 21 52;
 2 22 53;
 3 23 0;
 0 24 54;
 4 25 55;
 5 26 56;
 6 27 0;
 7 28 0;
 8 29 0;
 9 30 0;
 10 31 0;
 11 32 0;
 12 33 0;
 13 34 0;
 14 35 0;
 0 36 0;
 0 37 0;
 0 38 0;
 0 39 0;
 0 40 0;
 0 41 0;
 0 42 0;
 0 43 0;
 0 44 0;
 15 45 0;
 0 46 0;
 0 47 57;
 0 48 58;
 0 49 59;]';
M_.nstatic = 13;
M_.nfwrd   = 6;
M_.npred   = 11;
M_.nboth   = 4;
M_.nsfwrd   = 10;
M_.nspred   = 15;
M_.ndynamic   = 21;
M_.dynamic_tmp_nbr = [16; 0; 0; 0; ];
M_.equations_tags = {
  1 , 'name' , 'mc' ;
  2 , 'name' , 'zcap' ;
  3 , 'name' , 'rk' ;
  4 , 'name' , 'k' ;
  5 , 'name' , 'inve' ;
  6 , 'name' , 'q' ;
  7 , 'name' , 'c' ;
  8 , 'name' , 'y' ;
  9 , 'name' , '9' ;
  10 , 'name' , 'pinf' ;
  11 , 'name' , 'w' ;
  12 , 'name' , 'r' ;
  13 , 'name' , 'eps_a' ;
  14 , 'name' , 'eps_b' ;
  15 , 'name' , 'eps_g' ;
  16 , 'name' , 'eps_i' ;
  17 , 'name' , 'eps_r' ;
  18 , 'name' , 'eps_p' ;
  19 , 'name' , 'eps_w' ;
  20 , 'name' , 'kp' ;
  21 , 'name' , 'pinf_exp' ;
  22 , 'name' , 'pinf_exp_noshock' ;
  23 , 'name' , 'pinf_exp_tt1' ;
  24 , 'name' , 'dy' ;
  25 , 'name' , 'dc' ;
  26 , 'name' , 'dinve' ;
  27 , 'name' , 'dw' ;
  28 , 'name' , 'cpi_quarterly' ;
  29 , 'name' , 'robs' ;
  30 , 'name' , 'labobs' ;
  31 , 'name' , 'inf_fore_1_4' ;
};
M_.mapping.mc.eqidx = [1 10 ];
M_.mapping.zcap.eqidx = [2 4 8 ];
M_.mapping.rk.eqidx = [1 2 3 6 ];
M_.mapping.k.eqidx = [3 4 9 ];
M_.mapping.q.eqidx = [5 6 ];
M_.mapping.c.eqidx = [7 8 11 25 ];
M_.mapping.inve.eqidx = [5 8 20 26 ];
M_.mapping.y.eqidx = [8 9 12 24 ];
M_.mapping.lab.eqidx = [3 7 9 11 30 ];
M_.mapping.pinf.eqidx = [10 11 12 21 22 28 ];
M_.mapping.w.eqidx = [1 3 11 27 ];
M_.mapping.r.eqidx = [6 7 12 29 ];
M_.mapping.kp.eqidx = [4 20 ];
M_.mapping.eps_a.eqidx = [1 9 12 13 ];
M_.mapping.eps_b.eqidx = [6 7 14 ];
M_.mapping.eps_g.eqidx = [8 15 ];
M_.mapping.eps_i.eqidx = [5 16 20 ];
M_.mapping.eps_r.eqidx = [12 17 ];
M_.mapping.eps_p.eqidx = [10 18 ];
M_.mapping.eps_w.eqidx = [11 19 ];
M_.mapping.pinf_exp.eqidx = [6 7 10 11 21 31 ];
M_.mapping.labobs.eqidx = [30 ];
M_.mapping.robs.eqidx = [29 ];
M_.mapping.cpi_quarterly.eqidx = [28 ];
M_.mapping.dy.eqidx = [24 ];
M_.mapping.dc.eqidx = [25 ];
M_.mapping.dinve.eqidx = [26 ];
M_.mapping.dw.eqidx = [27 ];
M_.mapping.inf_fore_1_4.eqidx = [31 ];
M_.mapping.pinf_exp_noshock.eqidx = [22 23 ];
M_.mapping.pinf_exp_tt1.eqidx = [23 ];
M_.mapping.eta_a.eqidx = [13 ];
M_.mapping.eta_b.eqidx = [14 ];
M_.mapping.eta_g.eqidx = [15 ];
M_.mapping.eta_i.eqidx = [16 ];
M_.mapping.eta_r.eqidx = [17 ];
M_.mapping.eta_p.eqidx = [18 ];
M_.mapping.eta_w.eqidx = [19 ];
M_.mapping.eta_pi_exp.eqidx = [21 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [6 7 8 10 11 12 13 14 15 16 17 18 19 20 30 ];
M_.exo_names_orig_ord = [1:8];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(34, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(8, 1);
M_.params = NaN(34, 1);
M_.endo_trends = struct('deflator', cell(34, 1), 'log_deflator', cell(34, 1), 'growth_factor', cell(34, 1), 'log_growth_factor', cell(34, 1));
M_.NNZDerivatives = [122; 0; -1; ];
M_.static_tmp_nbr = [0; 0; 0; 0; ];
M_.params(4) = .025;
delta = M_.params(4);
M_.params(5) = 1.5;
phi_w = M_.params(5);
M_.params(27) = 0.18;
G = M_.params(27);
M_.params(2) = 10;
curvp = M_.params(2);
M_.params(1) = 10;
curvw = M_.params(1);
M_.params(9) = .24;
alpha = M_.params(9);
M_.params(21) = 1.5;
sigma_c = M_.params(21);
M_.params(16) = 1.5;
phi_p = M_.params(16);
M_.params(3) = 0;
rho_ga = M_.params(3);
M_.params(14) = 6.0144;
phi = M_.params(14);
M_.params(15) = 0.6361;
lambda = M_.params(15);
M_.params(18) = 0.8087;
xi_w = M_.params(18);
M_.params(22) = 1.9423;
sigma_l = M_.params(22);
M_.params(20) = 0.6;
xi_p = M_.params(20);
M_.params(17) = 0.3243;
iota_w = M_.params(17);
M_.params(19) = 0.47;
iota_p = M_.params(19);
M_.params(13) = 0.2696;
psi = M_.params(13);
M_.params(23) = 1.488;
r_pi = M_.params(23);
M_.params(26) = 0.8762;
rho = M_.params(26);
M_.params(25) = 0.0593;
r_y = M_.params(25);
M_.params(24) = 0.2347;
r_dy = M_.params(24);
M_.params(28) = 0.9977;
rho_a = M_.params(28);
M_.params(29) = 0.5799;
rho_b = M_.params(29);
M_.params(34) = 0.9957;
rho_g = M_.params(34);
M_.params(32) = 0.7165;
rho_i = M_.params(32);
M_.params(33) = 0;
rho_r = M_.params(33);
M_.params(30) = 0;
rho_p = M_.params(30);
M_.params(31) = 0;
rho_w = M_.params(31);
M_.params(12) = 0;
mu_p = M_.params(12);
M_.params(11) = 0;
mu_w = M_.params(11);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.4618)^2;
M_.Sigma_e(2, 2) = (1.8513)^2;
M_.Sigma_e(3, 3) = (0.6090)^2;
M_.Sigma_e(4, 4) = (0.6017)^2;
M_.Sigma_e(5, 5) = (0.2397)^2;
M_.Sigma_e(6, 6) = (0.1455)^2;
M_.Sigma_e(7, 7) = (0.2089)^2;
M_.params(22) = 1.1086;
sigma_l = M_.params(22);
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.param_vals = [estim_params_.param_vals; 14, 5.2, 2, 15, 3, 4, 1.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, 1.36, 0.25, 3, 3, 1.50, 0.375, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, 0.75, 0.001, 0.99, 1, 0.7, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, 0.59, 0.3, 0.95, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 20, 0.7813, 0.5, 0.99, 1, 0.5, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, 0.36, 0.01, 0.99, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 19, 0.58, 0.01, 0.99, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 13, 0.45, 0.01, 1, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, 1.61, 1.0, 3, 3, 1.25, 0.125, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 23, 1.88, 1.0, 3, 3, 1.5, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 26, 0.84, 0.5, 0.975, 1, 0.75, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 25, 0.11, 0.001, 0.5, 3, 0.125, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 24, 0.16, 0.001, 0.5, 3, 0.125, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 7, 0.67, 0.1, 2.0, 2, 0.625, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 6, 1.18, (-10.0), 10.0, 3, 0.0, 2.0, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 10, 0.41, 0.1, 0.8, 3, 0.4, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 9, 0.19, 0.01, 1.0, 3, 0.3, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 28, 0.92, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 29, 0.21, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 34, 0.99, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 32, 0.77, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 33, 0.06, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 30, 0.09, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 31, 0.94, .001, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, 0.4618, 0.01, 3, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 2.47, 0.025, 5, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, 0.5, 0.01, 3, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 0.4, 0.01, 3, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, 0.21, 0.01, 3, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, 0.16, 0.01, 3, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, 0.09, 0.01, 3, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 8, 0.09, 0.01, 3, 4, 0.1, 2, NaN, NaN, NaN ];
options_.cova_compute = 1;
options_.irf = 100;
options_.kalman_algo = 1;
options_.lik_init = 2;
options_.mh_drop = 0.5;
options_.mh_jscale = 0.3;
options_.mh_nblck = 1;
options_.mh_replic = 0;
options_.mode_compute = 0;
options_.nograph = true;
options_.prefilter = 0;
options_.presample = 4;
options_.datafile = 'expectations_dataset';
options_.mode_file = 'mcmc_param_values';
options_.optim_opt = '''MaxIter'',2000';
options_.first_obs = 71;
options_.order = 1;
var_list_ = {};
oo_recursive_=dynare_estimation(var_list_);
save('SW_Estimation_REE_expData_forMCMC_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('SW_Estimation_REE_expData_forMCMC_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('SW_Estimation_REE_expData_forMCMC_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('SW_Estimation_REE_expData_forMCMC_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('SW_Estimation_REE_expData_forMCMC_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('SW_Estimation_REE_expData_forMCMC_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('SW_Estimation_REE_expData_forMCMC_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
